"""
Django settings for canban project.

Generated by 'django-admin startproject'

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', '0') == '1'

# Allow all hosts if ALLOWED_HOSTS is set, otherwise use defaults
allowed_hosts_env = os.getenv('ALLOWED_HOSTS')
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',')]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# For Railway deployment, allow Railway domain
# Railway provides RAILWAY_PUBLIC_DOMAIN or we can use wildcard
railway_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN')
if railway_domain:
    ALLOWED_HOSTS.append(railway_domain)
elif os.getenv('RAILWAY_ENVIRONMENT'):
    # Allow all Railway subdomains
    ALLOWED_HOSTS.append('.railway.app')
    ALLOWED_HOSTS.append('.up.railway.app')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'canban.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'canban.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Support DATABASE_URL from Railway or other platforms
DATABASE_URL = os.getenv('DATABASE_URL')

# Check if we're on Railway (Railway sets RAILWAY_ENVIRONMENT)
IS_RAILWAY = os.getenv('RAILWAY_ENVIRONMENT') is not None

if DATABASE_URL:
    # Parse DATABASE_URL (format: postgresql://user:password@host:port/dbname)
    from urllib.parse import urlparse
    try:
        # Handle postgres:// and postgresql://
        if DATABASE_URL.startswith('postgres://'):
            DATABASE_URL = DATABASE_URL.replace('postgres://', 'postgresql://', 1)
        
        parsed = urlparse(DATABASE_URL)
        
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': parsed.path[1:] if parsed.path.startswith('/') else parsed.path,  # Remove leading '/'
                'USER': parsed.username,
                'PASSWORD': parsed.password,
                'HOST': parsed.hostname,
                'PORT': parsed.port or '5432',
            }
        }
        
        # Add SSL if specified in query parameters or if on Railway
        if (parsed.query and 'sslmode' in parsed.query) or IS_RAILWAY:
            DATABASES['default']['OPTIONS'] = {
                'sslmode': 'require'
            }
    except Exception as e:
        # Fallback to individual environment variables if parsing fails
        db_host = os.getenv('PGHOST') or os.getenv('DB_HOST')
        db_name = os.getenv('PGDATABASE') or os.getenv('DB_NAME', 'canban_db')
        db_user = os.getenv('PGUSER') or os.getenv('DB_USER', 'canban_user')
        db_password = os.getenv('PGPASSWORD') or os.getenv('DB_PASSWORD', 'canban_password')
        db_port = os.getenv('PGPORT') or os.getenv('DB_PORT', '5432')
        
        if not db_host and IS_RAILWAY:
            raise ValueError(
                "DATABASE_URL or database connection variables must be set. "
                "Please ensure PostgreSQL service is connected in Railway."
            )
        
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': db_name,
                'USER': db_user,
                'PASSWORD': db_password,
                'HOST': db_host or 'db',  # Only use 'db' as fallback for local development
                'PORT': db_port,
            }
        }
        
        if IS_RAILWAY:
            DATABASES['default']['OPTIONS'] = {
                'sslmode': 'require'
            }
else:
    # Use individual environment variables or defaults
    # Railway uses PGHOST, PGDATABASE, PGUSER, PGPASSWORD, PGPORT
    db_host = os.getenv('PGHOST') or os.getenv('DB_HOST')
    db_name = os.getenv('PGDATABASE') or os.getenv('DB_NAME', 'canban_db')
    db_user = os.getenv('PGUSER') or os.getenv('DB_USER', 'canban_user')
    db_password = os.getenv('PGPASSWORD') or os.getenv('DB_PASSWORD', 'canban_password')
    db_port = os.getenv('PGPORT') or os.getenv('DB_PORT', '5432')
    
    # On Railway, require database connection variables
    if IS_RAILWAY and not db_host:
        raise ValueError(
            "DATABASE_URL or database connection variables (PGHOST, PGDATABASE, etc.) must be set. "
            "Please ensure PostgreSQL service is connected in Railway and DATABASE_URL is available."
        )
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host or 'db',  # Only use 'db' as fallback for local development
            'PORT': db_port,
        }
    }
    
    if IS_RAILWAY:
        DATABASES['default']['OPTIONS'] = {
            'sslmode': 'require'
        }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

